name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install

    # If you ever add a testing framework (like Jest) later, you uncomment this:
    # - name: Run Tests
    #   run: npm test

    - name: Trigger Render Deployment
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
